### ISSUE TITLE
temp list 

### ISSUE THREAD

**Issue by AdityaKarpe** [chetankoli1/GSTbillingApp-android#13]
tu left la ₹ symbol tevla ahe toh correct ahe bass ha symbol add kar "/-"
ani temp list ashi disli pahije 

product name : value 
Quantity : value 
HSN/SAC : value 
Product Price : value 

eg. 
Product Name : Lays 
Price : ₹200/-
Quantity : 2
HSN/SAC : Ly243A

**Comment by chetankoli1** [comment]
this essue is done.
